### ISSUE TITLE
mem: 1g or 2g

### ISSUE THREAD

**Issue by vchong** [Linaro/poplar-tools#12]
Regarding https://github.com/Linaro/poplar-tools/blob/latest/poplar_recovery_builder.sh#L554, should it be 1G or 2G, or does it not really matter?

**Comment by alexelder** [comment]
On 10/29/2017 05:27 AM, vchong wrote:
> Regarding https://github.com/Linaro/poplar-tools/blob/latest/poplar_recovery_builder.sh#L554, should it be 1G or 2G, or does it not really matter?

The original Tocoding board has 1GB.  The original HiSilicon board
and (reportedly) the new Tocoding board has 2GB.

Whether it matters is a question I've been meaning to investigate
for *months* and I never got the answer.  I think if you have 2GB and
the command line says 1GB, then it *might* limit memory use to 1GB,
in which case it should be 2GB.

But I'm pretty sure the bootloader discovers what's physically present
on the board, and my question is, does that affect what it tells the
kernel in its command line?  And how does that relate to the memory
regions it tells the kernel about?  And...  what does the kernel do
with these several sources of information about the memory size.

					-Alex

**Comment by shawnguo2** [comment]
Here is my understanding.  U-Boot runs a simple memory test and determines the actually available RAM size, and then overwrite the one in device tree with it.  So kernel will always read the correct RAM size from DT.  The "mem=1G" kernel parameter only makes sense for 2GB board, if for some reason (mostly testing), we want to limit the available RAM to 1GB for kernel to use.

**Comment by vchong** [comment]
Thanks!
Is there a way to differentiate between the old Tocoding, Hisi and new Tocoding boards?

**Comment by shawnguo2** [comment]
@vchong Hisi and new Tocoding boards are identical.  What do you need to handle differently between old and new Tocoding boards?

**Comment by vchong** [comment]
@shawnguo2 Trying to see if it's ok to put load op-tee binary in high memory. Do we have to make everything compatible with 1g board as well? If so, that means we shouldn't load anything in high memory.

**Comment by shawnguo2** [comment]
@vchong Yes, we need to support 1G board as well.  If necessary, we can have a build option for 1G.  But we want to avoid that in general.
