### ISSUE TITLE
Permission denied (publickey) for dev-private-git.linaro.org

### ISSUE THREAD

**Issue by w20088** [Linaro/poplar-tools#4]
When I download code to add Poplar support for Android, the dev-private-git.linaro.org git server does't have my ssh publickey.  How can I add my ssh publickey to the server? Is it possiable to add those code to github?

git clone \
    ssh://git@dev-private-git.linaro.org/aspen/staging/device/linaro/poplar.git

**Comment by gvalante** [comment]
Hello;

Sorry for the confusion.   These instructions should be removed for now.    We're working on releasing this public, but the code has not gone thru review for release.   When it is reviewed, we will provide access on GitHub.

Thanks;

Glen

**Comment by w20088** [comment]
Thanks. Looking forward to the formal release.
